//Socket file , where we wrap the expresss app unto it to have https methods
import { Server } from "socket.io";
import { Server as Httpserver } from "http";

export const initializeSocket = (server: Httpserver) => {
    // 1. Initialize the Socket.io server

    const io = new Server(server, {
        cors: {
            origin: "*",
            methods: ["GET", "POST"]
        }
    });

    /*
        =====================================================================
        THE PIPELINE PHASE 2 & 3: Connection & Identification
        =====================================================================
        - 'io.on("connection")' is the Watchman overseeing the whole building.
        - He is waiting for the abstract *event* of ANY guest arriving.
        - When a VIP guest asks for a WebSocket upgrade and connects, the Watchman:
          1. Generates a unique 20-character socket.id (e.g. YE4A_ZX...)
          2. Creates a unique Backend Walkie-Talkie (the 'socket' parameter below)
          3. Tells the client their ID.
    */
    io.on("connection", (socket) => {
        console.log("A VIP guest arrived! We generated their nametag/ID:", socket.id);


        //Join room
        socket.on("join-room", (roomId: string) => {
            /* 
            Now we are putting the socket connection wich is generated by backend in the room and its id is generated by froned and 
            sent to backend in the already established tcp socket connection
            */
            if (!roomId) {
                throw new Error("The room id is not avaliable ")
            }
            socket.join(roomId)
            /* Imagine the sockets are the frontend and for that sockets the backend gives uid for that client 
            and when we have a room ,the backend takes that client and puts in the room id sent by the forntend
            */
            console.log(`Guest [${socket.id}] entered Room: ${roomId}`);
        })


        //Recieve the message from backend and send to frontend
        socket.on("send-chat-message", ({ roomId, message, senderName }) => {
            //Broadcast this recieved message to all room 
            socket.to(roomId).emit("receive-chat-message", {
                senderId: socket.id,
                senderName,
                message
            })
        })


        socket.on("send-crdt-packet", ({ roomId, packet }) => {
            //when we recieve the updated code from the frontend Yjs we take it and braodcast to all the users in the room and again the frontend yjs updates its ui
            socket.to(roomId).emit("receive-crdt-packet", packet)
        })

        /*
            =====================================================================
            THE PIPELINE Phase 4: Full-Duplex Listening
            =====================================================================
            - Now we have a permanent 0-latency TCP pipe.
            - The Watchman keeps his walkie-talkie to his ear, listening specifically for
              this guest to crash their walkie-talkie (e.g., closing the browser tab).
        */
        socket.on("disconnect", () => {
            console.log("Guest ripped up their walkie-talkie (disconnected):", socket.id);
        })
    })

    return io;
}





